### ISSUE TITLE
Scala: Test failures in adts

### ISSUE THREAD

**Issue by syntakker** [ahrefs/atd#199]
There are test failures in the scala section in atds (however possibly specific to the version of Scala used).

To reproduce (on `ocaml/opam2` docker image):
`docker run -it ocaml/opam2:ubuntu bash`
Install dependencies:
```bash
opam install dune
cd ..
git clone https://github.com/ahrefs/atd.git
cd atd/
dune external-lib-deps --missing @@default
opam install biniou easy-format re yojson
sudo apt-get install m4
opam install menhir
sudo apt-get install scala
sudo apt-get install openjdk-11-jdk
```

Build and run tests;
```bash
opam@216b8d8251bd:~/atd$ make clean                                 
dune clean
opam@216b8d8251bd:~/atd$ make all
dune build
opam@216b8d8251bd:~/atd$ make test
dune runtest
test_atdgen_main alias atdgen/test/runtest
Warning: skipping field b2 (def: File "test.atd", line 98, characters 12-40)
Warning: skipping field b3 (def: File "test.atd", line 98, characters 12-40)
Warning: skipping field b4 (def: File "test.atd", line 98, characters 12-40)
Warning: skipping field b5 (def: File "test.atd", line 98, characters 12-40)
    run_test alias atds/test/runtest (exit 1)
(cd _build/default/atds/test && ./run_test.sh)
test.scala:64: error: identifier expected but ')' found.
) extends Atds {
^
test.scala:241: error: ':' expected but '}' found.
}
^
two errors found
make: *** [Makefile:7: test] Error 1
```

Cause for this was a comma in some inappropriate places, like this:
```scala
...
  final_ : Option[Int],
  kase : String,
  l2 : List[RecordWithDefaults],
) extends Atds {
...
```

After fixing `test.scala` in the `_build` directory, the file compiled with these changes:
```patch
opam@216b8d8251bd:~/atd/_build/default/atds/test$ diff test.expected.scala test.scala 
63c63
<   opt : Option[Boolean],
---
>   opt : Option[Boolean]
68c68
<     "opt" := opt,
---
>     "opt" := opt
141c141
<   l2 : List[RecordWithDefaults],
---
>   l2 : List[RecordWithDefaults]
154c154
<     "l2" := l2,
---
>     "l2" := l2
164c164
<   e : E,
---
>   e : E
173c173
<     "e" := e,
---
>     "e" := e
184c184
<   more : String,
---
>   more : String
194c194
<     "more" := more,
---
>     "more" := more
231c231
<   state : String,
---
>   state : String
237c237
<     "state" := state,
---
>     "state" := state
```
(Note that the misplaced commas are also present in `test.expected.scala`)

However, the scala tests still failed:
```
opam@216b8d8251bd:~/atd/_build/default/atds/test$ ./run_test.sh                       
JUnit version 4.8.2
.E.E.E
Time: 0.101
There were 3 failures:
1) testDefaults(AtdsTest)
java.lang.NoSuchMethodError: 'void scala.Product.$init$(scala.Product)'
        at argonaut.Json.<init>(Json.scala:13)
        at argonaut.JNull$.<init>(Json.scala:479)
        at argonaut.JNull$.<clinit>(Json.scala)
        ...
```

...which however might be specific to versions of dependencies and/or versions of Scala and Java used here:
```bash
opam@216b8d8251bd:~/atd/_build/default/atds/test$ scala
Welcome to Scala 2.11.12 (OpenJDK 64-Bit Server VM, Java 11.0.4).
```
and `openjdk-11-jdk`, as stated above.

I will look into dependency versions to see how to fix the latter issue.

**Comment by syntakker** [comment]
Updating to Scala 2.12.3 resolves the issue entirely, no test failures anymore.
Still the extra commas seem to be misplaced.

**Comment by aij** [comment]
Scala has had support for trailing commas for quite a while now, so I
didn't think emitting them would be a problem. I never tried this with
Scala 2.11, but if you want to make it work, PRs are welcome.

**Comment by syntakker** [comment]
Trailing commas are fixed in https://github.com/ahrefs/atd/pull/200.

For those interested, here an updated version of all the steps for a working build environment:

To reproduce (on ocaml/opam2 docker image):
```
docker run -it ocaml/opam2:ubuntu bash
```
Install dependencies:
```
opam install dune
cd ..
git clone https://github.com/ahrefs/atd.git
cd atd/
dune external-lib-deps --missing @@default
opam install biniou easy-format re yojson
sudo apt-get install m4
opam install menhir
sudo wget https://downloads.lightbend.com/scala/2.12.3/scala-2.12.3.deb
sudo dpkg -i scala-2.12.3.deb
sudo apt-get update
sudo apt-get install scala
```
(Scala update from here: https://gist.github.com/malzzz/15639fc36d069490b7709be2f3a4d522)

**Comment by syntakker** [comment]
Works for me now for both Scala 2.11 and 2.12 (tested versions: 2.11.12 and 2.12.3).

**Comment by syntakker** [comment]
Fixed.
